[build]
  command = "npm run build"
  publish = ".next"

# Only redirect www to non-www for the main domain
[[redirects]]
  from = "https://www.kwslinkhout.be/*"
  to = "https://kwslinkhout.be/:splat"
  status = 301
  force = true
